---
- name: Copy Website to Web Servers
  hosts: web
  tasks:
  - name: Copy Website
    become: yes
    ansible.builtin.copy: 
      remote_src: yes
      src: file:///home/justincase/Downloads/8Assignment.html
      dest: /etc/8assignment.html
      owner: justincase
      mode: '0644'