---
- name: Remove Users
  hosts: linux
  tasks:
  - name: Remove Jacob
    become: yes
    ansible.builtin.user:
      name: Jacob
      state: absent
  - name: Remove Aldon
    become: yes
    ansible.builtin.user:
      name: Aldon
      state: absent

- name: LAMP uninstall
  hosts: web
  tasks:
  - name: Uninstall Apache2
    become: yes
    ansible.builtin.apt:
      name: apache2
      state: absent

- name: Uninstall MariaDB
  hosts: db
  tasks:
  - name: Uninstall MariaDB-Server
    become: yes
    ansible.builtin.apt:
      name: mariadb-server
      state: absent