---
- name: Setup LAMP Stack
  hosts: linux
  tasks:
  - name: Create user "Jacob"
    ansible.builtin.user:
      name: Jacob
      password: "gbnjklzdujth3890"
    become: yes
  - name: Create user "Aldon"
    ansible.builtin.user:
      name: Aldon
      password: "gbnjklzdujth3890"
    become: yes

- name: Install/Setup Apache
  hosts: web
  tasks:
  - name: Install Apache2
    become: yes
    ansible.builtin.apt:
      update_cache: yes
      name: apache2
      state: present
  - name: Setup Apache
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes
  - name: Open firewall for website
    become: yes
    ufw:
      rule: allow
      port: '443'
      proto: tcp
    notify:
      - reload-firewall
  handlers:
    - name: reload-firewall
      become: yes
      ufw:
        state: reloaded

- name: Install/Setup MariaDB
  hosts: db
  tasks:
  - name: Install MariaDB
    become: yes  
    ansible.builtin.apt:
      update_cache: yes
      name: mariadb-server
      state: present
  - name: Setup MariaDB
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes