#!usr/bin/env python3
#This is a guess the number program
import random

random_number = random.randint(1, 10)
answer = int(input(print("Enter the number you think it is: ")))
if answer != random_number:
    while answer != random_number:
        if answer > random_number:
            print("Too high, try again")
            answer = int(input(print("Enter your next guess: ")))
        elif answer < random_number:
            print("Too low, try again")
            answer = int(input(print("Enter your next guess: ")))
    print("Congratulations")
else:
    print("Congratulations!")